# Generated by Django 5.2.17 on 2026-08-31 20:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaletConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('chalet_name', models.CharField(default='Chalet 101', max_length=120)),
                ('chalet_number', models.CharField(default='101', max_length=30)),
                ('persona_name', models.CharField(default='Wazen', max_length=80)),
                ('welcome_message', models.TextField(blank=True)),
                ('property_facts', models.JSONField(blank=True, default=dict)),
                ('enabled_services', models.JSONField(blank=True, default=list)),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('current_stay_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KioskAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_id', models.UUIDField(db_index=True)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event', models.CharField(choices=[('chat_queued', 'Chat queued'), ('agent_started', 'Agent started'), ('tool_called', 'Tool called'), ('agent_completed', 'Agent completed'), ('agent_failed', 'Agent failed'), ('stay_reset', 'Stay reset')], max_length=40)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KioskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_id', models.UUIDField(db_index=True)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('streaming', 'Streaming'), ('complete', 'Complete'), ('failed', 'Failed')], default='complete', max_length=16)),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('tool_call_id', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['stay_id', 'created_at'], name='kiosk_agent_stay_id_53348a_idx')],
            },
        ),
    ]
