# Generated by Django 5.2.17 on 2026-09-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_agent', '0002_sunset_resort_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaletconfig',
            name='saas_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chaletconfig',
            name='saas_integration_token',
            field=models.CharField(blank=True, help_text='X-Kiosk-Token / X-API-Key for SaaS', max_length=500),
        ),
        migrations.AddField(
            model_name='chaletconfig',
            name='saas_integration_url',
            field=models.URLField(blank=True, help_text='Full SaaS endpoint URL, e.g. https://tenant.raddadoman.com/api/kiosk/requests/', max_length=500),
        ),
        migrations.AddField(
            model_name='chaletconfig',
            name='saas_tenant_subdomain',
            field=models.CharField(blank=True, help_text='Tenant subdomain if SaaS URL is public schema', max_length=63),
        ),
        migrations.AddField(
            model_name='chaletconfig',
            name='saas_timeout_seconds',
            field=models.FloatField(default=5.0),
        ),
    ]
