# Generated by Django 5.2.17 on 2026-09-18 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk_agent", "0004_realtime_sessions_staff_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("ac", "AC"), ("fan", "Fan"), ("lights", "Lights"), ("other", "Other")],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AlterField(
            model_name="kioskauditlog",
            name="event",
            field=models.CharField(
                choices=[
                    ("chat_queued", "Chat queued"),
                    ("agent_started", "Agent started"),
                    ("tool_called", "Tool called"),
                    ("agent_completed", "Agent completed"),
                    ("agent_failed", "Agent failed"),
                    ("stay_reset", "Stay reset"),
                    ("remote_pressed", "Remote pressed"),
                    ("remote_failed", "Remote failed"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="RemoteControl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("template_slug", models.SlugField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "voice_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Allow voice tools to press buttons on this remote.",
                    ),
                ),
                (
                    "guest_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Show this remote on the kiosk guest panel.",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remotes",
                        to="kiosk_agent.remotetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="RemoteButton",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=80)),
                ("icon", models.CharField(blank=True, max_length=40)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("row", models.PositiveSmallIntegerField(default=0)),
                ("column", models.PositiveSmallIntegerField(default=0)),
                ("command_url", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_confirmation", models.BooleanField(default=False)),
                (
                    "remote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="kiosk_agent.remotecontrol",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "row", "column", "id"),
                "constraints": [
                    models.UniqueConstraint(fields=("remote", "key"), name="uniq_remote_button_key"),
                    models.UniqueConstraint(
                        fields=("remote", "row", "column"),
                        name="uniq_remote_button_position",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RemoteTemplateButton",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=80)),
                ("icon", models.CharField(blank=True, max_length=40)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("row", models.PositiveSmallIntegerField(default=0)),
                ("column", models.PositiveSmallIntegerField(default=0)),
                ("requires_confirmation", models.BooleanField(default=False)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="kiosk_agent.remotetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "row", "column", "id"),
                "constraints": [
                    models.UniqueConstraint(fields=("template", "key"), name="uniq_template_button_key"),
                    models.UniqueConstraint(
                        fields=("template", "row", "column"),
                        name="uniq_template_button_position",
                    ),
                ],
            },
        ),
    ]
