# Generated by Django 5.2.17 on 2026-09-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_agent', '0011_remove_remotecontrol_esp32_routing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotebutton',
            name='icon',
            field=models.CharField(blank=True, choices=[('power', 'Power'), ('power_speed', 'Power / Speed'), ('plus', 'Plus'), ('minus', 'Minus'), ('mode', 'Mode'), ('fan', 'Fan'), ('light', 'Light')], max_length=40),
        ),
        migrations.AlterField(
            model_name='remotebutton',
            name='key',
            field=models.SlugField(choices=[('power_on', 'Power On'), ('power_off', 'Power Off'), ('power_speed', 'Power / Speed'), ('speed_up', 'Speed Up'), ('speed_down', 'Speed Down'), ('temp_up', 'Temperature Up'), ('temp_down', 'Temperature Down'), ('mode', 'Mode'), ('fan', 'Fan'), ('on', 'On'), ('off', 'Off'), ('dim', 'Dim'), ('bright', 'Bright')], max_length=80),
        ),
        migrations.AlterField(
            model_name='remotetemplatebutton',
            name='icon',
            field=models.CharField(blank=True, choices=[('power', 'Power'), ('power_speed', 'Power / Speed'), ('plus', 'Plus'), ('minus', 'Minus'), ('mode', 'Mode'), ('fan', 'Fan'), ('light', 'Light')], max_length=40),
        ),
        migrations.AlterField(
            model_name='remotetemplatebutton',
            name='key',
            field=models.SlugField(choices=[('power_on', 'Power On'), ('power_off', 'Power Off'), ('power_speed', 'Power / Speed'), ('speed_up', 'Speed Up'), ('speed_down', 'Speed Down'), ('temp_up', 'Temperature Up'), ('temp_down', 'Temperature Down'), ('mode', 'Mode'), ('fan', 'Fan'), ('on', 'On'), ('off', 'Off'), ('dim', 'Dim'), ('bright', 'Bright')], max_length=80),
        ),
    ]
