# Generated by Django 5.2.17 on 2026-09-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_agent', '0012_alter_remotebutton_icon_alter_remotebutton_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotebutton',
            name='icon',
            field=models.CharField(blank=True, choices=[('power', 'Power'), ('power_speed', 'Power / Speed'), ('plus', 'Plus'), ('minus', 'Minus'), ('mode', 'Mode'), ('fan', 'Fan'), ('light', 'Light'), ('up', 'Up'), ('down', 'Down'), ('left', 'Left'), ('right', 'Right'), ('ok', 'OK / Select'), ('back', 'Back'), ('home', 'Home'), ('menu', 'Menu'), ('settings', 'Settings'), ('info', 'Information'), ('guide', 'Guide'), ('input', 'Input / Source'), ('play', 'Play'), ('pause', 'Pause'), ('stop', 'Stop'), ('record', 'Record'), ('rewind', 'Rewind'), ('fast_forward', 'Fast Forward'), ('previous', 'Previous'), ('next', 'Next'), ('volume', 'Volume'), ('volume_up', 'Volume Up'), ('volume_down', 'Volume Down'), ('mute', 'Mute'), ('channel_up', 'Channel Up'), ('channel_down', 'Channel Down'), ('cool', 'Cool'), ('heat', 'Heat'), ('dry', 'Dry'), ('swing_vertical', 'Vertical Swing'), ('swing_horizontal', 'Horizontal Swing'), ('turbo', 'Turbo'), ('sleep', 'Sleep'), ('timer', 'Timer'), ('eco', 'Eco'), ('number_0', 'Number 0'), ('number_1', 'Number 1'), ('number_2', 'Number 2'), ('number_3', 'Number 3'), ('number_4', 'Number 4'), ('number_5', 'Number 5'), ('number_6', 'Number 6'), ('number_7', 'Number 7'), ('number_8', 'Number 8'), ('number_9', 'Number 9')], max_length=40),
        ),
        migrations.AlterField(
            model_name='remotetemplatebutton',
            name='icon',
            field=models.CharField(blank=True, choices=[('power', 'Power'), ('power_speed', 'Power / Speed'), ('plus', 'Plus'), ('minus', 'Minus'), ('mode', 'Mode'), ('fan', 'Fan'), ('light', 'Light'), ('up', 'Up'), ('down', 'Down'), ('left', 'Left'), ('right', 'Right'), ('ok', 'OK / Select'), ('back', 'Back'), ('home', 'Home'), ('menu', 'Menu'), ('settings', 'Settings'), ('info', 'Information'), ('guide', 'Guide'), ('input', 'Input / Source'), ('play', 'Play'), ('pause', 'Pause'), ('stop', 'Stop'), ('record', 'Record'), ('rewind', 'Rewind'), ('fast_forward', 'Fast Forward'), ('previous', 'Previous'), ('next', 'Next'), ('volume', 'Volume'), ('volume_up', 'Volume Up'), ('volume_down', 'Volume Down'), ('mute', 'Mute'), ('channel_up', 'Channel Up'), ('channel_down', 'Channel Down'), ('cool', 'Cool'), ('heat', 'Heat'), ('dry', 'Dry'), ('swing_vertical', 'Vertical Swing'), ('swing_horizontal', 'Horizontal Swing'), ('turbo', 'Turbo'), ('sleep', 'Sleep'), ('timer', 'Timer'), ('eco', 'Eco'), ('number_0', 'Number 0'), ('number_1', 'Number 1'), ('number_2', 'Number 2'), ('number_3', 'Number 3'), ('number_4', 'Number 4'), ('number_5', 'Number 5'), ('number_6', 'Number 6'), ('number_7', 'Number 7'), ('number_8', 'Number 8'), ('number_9', 'Number 9')], max_length=40),
        ),
    ]
