# Generated by Django 5.2.17 on 2026-09-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_agent', '0013_alter_remotebutton_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotebutton',
            name='key',
            field=models.SlugField(max_length=80),
        ),
        migrations.AlterField(
            model_name='remotetemplatebutton',
            name='key',
            field=models.SlugField(max_length=80),
        ),
    ]
